# Generated by Django 5.2.6 on 2025-10-18 14:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_order_dishesinorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishesinorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
