# Generated by Django 5.2.6 on 2025-10-18 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0003_dishesinorder_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishesinorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_app.order'),
        ),
    ]
