# Generated by Django 5.2.6 on 2025-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0005_remove_order_full_name_order_email_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Коментар'),
        ),
    ]
